### PR TITLE
Fix race conditions in mock methods and mock properties

### LINKED ISSUE #121: [Bug] Mock doesn't record every invocation when invoked simultaneously across threads
### Swift Version

6.0

### Package Version

0.2.1

### Bug Description

I ran unit tests for a method that awaited a task group. In the task group, in each task, I call a method on a dependency. In the tests, I injected a mock and asserted that the mock's method was called a certain number of times (in this case twice), and that the invocations array contained the expected arguments. Instead of always getting two invocations, I sometimes only got one. The method's call count also sometimes came back as one instead of two.

### Steps to Reproduce

Create a task group that adds a certain number of tasks and have each task call a method on a dependency. Make the work inside the tasks synchronous to ensure they all finish at the same time. Inject a mock and assert that the mock's method is called more than once.

### Expected Behavior

_No response_

### Actual Behavior

_No response_

### Stack Trace / Logs

```shell

```

### Additional Context

Inside the mock method's `recordInput` method, the call count and invocations are being accessed via wrapper properties that then access locked backing properties. The problem is that the wrapper properties' getters and setters are being protected by the lock separately, so:

Thread 1: Lock; read `callCount`; see it’s 0; unlock
Thread 2: Lock; read `callCount`; see it’s 0; unlock
Thread 1: Lock; set `callCount` to 1; unlock
Thread 2: Lock; set `callCount` to 1; unlock

The same thing happens with `invocations`.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by graycampbell**
## 📝 Summary

- Updated all the mock method and mock property backing types to read and write data directly to their private, locked properties instead of to the locked properties' public-facing wrappers to prevent race conditions.
- Updated unit tests to validate that the race conditions are no longer possible.

## 🛠️ Type of Change

- [x] Bug fix (change that fixes an issue)
- [ ] New feature (change that adds functionality)
- [ ] Breaking change (bug fix or feature that is not backwards compatible)
- [ ] Documentation (DocC, API docs, markdown files, templates, etc.)
- [ ] Testing (new tests, updated tests, etc.)
- [ ] Refactoring or code formatting (no logic changes)
- [ ] Updating dependencies (Swift packages, Homebrew, etc.)
- [ ] CI/CD (change to automated workflows)
- [ ] Chore (other maintenance)

## 🧪 How Has This Been Tested?

- Updated unit tests to validate that the race conditions are no longer possible by using a barrier to force concurrent execution across tasks.
- Added new unit tests.

## 🔗 Related PRs or Issues 

- Fixes #121

## ✅ Checklist

- [x] I have added relevant tests
- [x] I have verified all tests pass
- [x] I have formatted my code using `SwiftFormat`
- [x] I have updated documentation (if needed)
- [x] I have added the appropriate label to my PR
- [x] I have read the [contributing guidelines](https://github.com/fetch-rewards/swift-mocking/blob/main/CONTRIBUTING.md)
- [x] I agree to follow this project's [Code of Conduct](https://github.com/fetch-rewards/swift-mocking/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: Sources/Mocking/Models/MockMethods/MockReturningMethods/MockReturningNonParameterizedAsyncMethod/MockReturningNonParameterizedAsyncMethod.swift [hunk 1]
```diff
@@ -103,13 +103,17 @@ public final class MockReturningNonParameterizedAsyncMethod<ReturnValue> {
     /// - Returns: A value, if ``implementation-swift.property`` returns a
     ///   value.
     private func invoke() async -> ReturnValue {
-        self.callCount += 1
+        self._callCount.withLockUnchecked { callCount in
```
Comment (pjtnt11) [inline Sources/Mocking/Models/MockMethods/MockReturningMethods/MockReturningNonParameterizedAsyncMethod/MockReturningNonParameterizedAsyncMethod.swift:106]: Why does this need to be unchecked? This is just an `Int`, right?

File: Sources/Mocking/Models/MockMethods/MockReturningMethods/MockReturningNonParameterizedAsyncMethod/MockReturningNonParameterizedAsyncMethod.swift [hunk 2]
```diff
@@ -103,13 +103,17 @@ public final class MockReturningNonParameterizedAsyncMethod<ReturnValue> {
     /// - Returns: A value, if ``implementation-swift.property`` returns a
     ///   value.
     private func invoke() async -> ReturnValue {
```
Comment (pjtnt11) [inline Sources/Mocking/Models/MockMethods/MockReturningMethods/MockReturningNonParameterizedAsyncMethod/MockReturningNonParameterizedAsyncMethod.swift:105]: It might be OK, but I think this way of solving this issues opens up another race condition where the count and the returned values are not up to date with each other. I think you would want both of them to happen on the same lock

**Comment by graycampbell** [comment]
In regards to the [Codecov Report](https://github.com/fetch-rewards/swift-mocking/pull/122#issuecomment-3127718345), I didn't add any new tests in this PR. It's already a very big PR, so I decided to only update existing tests. I will add new tests for all the mock property accessors in a separate PR later this week.

File: Tests/MockingTests/TestHelpers/TestBarrier.swift [hunk 3]
```diff
@@ -0,0 +1,179 @@
...
+/// await withTaskGroup(of: Void.self) { group in
+///     for _ in 0..<taskCount {
+///         group.addTask {
+///             await barrier.wait() // All tasks wait here
+///             someOperation()      // All execute simultaneously
+///         }
+///     }
+/// }
+/// ```
+actor TestBarrier {
```
Comment (pjtnt11) [inline Tests/MockingTests/TestHelpers/TestBarrier.swift:29]: Maybe your testing shows differently, but I don't think this solves the issue you were facing here: calling `continuation.resume` does not immediately resume the continuation. Instead it *schedules* the continuation to resume based on the lightest priority task. I don't believe this is any different from starting a bunch of tasks in terms of scheduling.

**Review by pjtnt11 — APPROVED** [review]
Some things I think we can improve but otherwise looks good ✅

File: Sources/Mocking/Models/MockMethods/MockReturningMethods/MockReturningNonParameterizedAsyncMethod/MockReturningNonParameterizedAsyncMethod.swift (hunk 2 above)
Comment (graycampbell) [reply Sources/Mocking/Models/MockMethods/MockReturningMethods/MockReturningNonParameterizedAsyncMethod/MockReturningNonParameterizedAsyncMethod.swift:105]: Good callout. I don't think that would generally be an issue in practice - that should only be an issue if you were trying to write an expectation in between different tasks in a task group completing - but it would be better to have everything accessed on the same lock. I'll create an issue.

Comment (graycampbell) [reply Sources/Mocking/Models/MockMethods/MockReturningMethods/MockReturningNonParameterizedAsyncMethod/MockReturningNonParameterizedAsyncMethod.swift:105]: Issue created - #125.

File: Tests/MockingTests/TestHelpers/TestBarrier.swift (hunk 3 above)
Comment (graycampbell) [reply Tests/MockingTests/TestHelpers/TestBarrier.swift:29]: Issue created - #126.
